---
# facts can be used with conditions and decision making playbooks

- name: Print Facts
  hosts: all
  tasks:
    - name: Print OS name
      debug:
        var: ansible_distribution

    - name: Print selinux mode
      debug:
        var: ansible_selinux.mode

    - name: Print memory details
      debug:
        var: ansible_memory_mb

    - name: Print RAM memory
      debug:
        var: ansible_memory_mb.real.free

    - name: Print Processor name
      debug:
        var: ansible_processor[2]
